### ISSUE TITLE
Default tolerance value not matching comments

### ISSUE THREAD

**Issue by arurke** [TriScale-Anon/triscale#2]
The comments for default `tolerance` value says consistently 1 %, while code is using both 5 % and 1%, see e.g. https://github.com/TriScale-Anon/triscale/blob/9627caa7a5e6ec32551c38335fde881fe9530134/triscale.py#L516

**Comment by TriScale-Anon** [comment]
Fixed! Thanks :-)

**Comment by arurke** [comment]
@TriScale-Anon The fix for this issue reverted the change from https://github.com/TriScale-Anon/triscale/pull/1.

See https://github.com/TriScale-Anon/triscale/commit/a3300f5384b6682711f228f2e4e6d9bea3a909b2#diff-5d6a342b320c918c6a910ae0e1f63b968f1bea8013188186b09357d9bbe4f113L837
